#!/usr/bin/env python3
"""Generate valid GEMM kernel configurations and output a CMake include file."""

import argparse
import os

def smem_bytes(bm, bn, bk, num_stages, split_k):
    """Compute shared memory bytes for a config."""
    # X + W tiles across stages
    tile_bytes = num_stages * (bm * bk + bk * bn) * 2  # bf16 = 2 bytes
    # barriers: 2 arrays of NUM_STAGES uint64_t
    barrier_bytes = 2 * num_stages * 8
    # Non-split-K has Y_out staging buffer in smem
    if split_k == 1:
        y_out_bytes = bm * bn * 2
    else:
        y_out_bytes = 0
    return tile_bytes + y_out_bytes + barrier_bytes

def config_name(bm, bn, bk, stages, cwg, wm, wn, sk):
    return f"bm{bm}_bn{bn}_bk{bk}_s{stages}_cwg{cwg}_wm{wm}_wn{wn}_sk{sk}"

def generate_configs(max_smem_kb=128):
    max_smem = max_smem_kb * 1024
    configs = []

    for bm in [64, 128]:
        for bn in [64, 128]:
            for bk in [64]:  # BK*sizeof(bf16) must >= SWIZZLE_128B (128 bytes)
                for cwg in [1, 2]:
                    num_consumer_warps = cwg * 4
                    for sk in [1, 2]:
                        for stages in [4, 3, 2]:
                            for wm in range(16, bm + 1, 16):
                                if bm % wm != 0:
                                    continue
                                for wn in range(8, bn + 1, 8):
                                    if bn % wn != 0:
                                        continue
                                    warps_m = bm // wm
                                    warps_n = bn // wn
                                    if warps_m * warps_n != num_consumer_warps:
                                        continue
                                    # Pick max stages that fits in smem
      
                                    sb = smem_bytes(bm, bn, bk, stages, sk)
                                    if sb > max_smem:
                                        continue
                                    name = config_name(bm, bn, bk, stages, cwg, wm, wn, sk)
                                    configs.append((bm, bn, bk, stages, cwg, wm, wn, sk, name))
    return configs

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, help="Output .cmake file path")
    parser.add_argument("--max-smem-kb", type=int, default=128)
    args = parser.parse_args()

    configs = generate_configs(args.max_smem_kb)

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w") as f:
        f.write("# Auto-generated by gen_configs.py — do not edit\n")
        f.write(f"# {len(configs)} configs (max smem {args.max_smem_kb} KB)\n\n")
        f.write("set(GEMM_CONFIGS\n")
        for bm, bn, bk, stages, cwg, wm, wn, sk, name in configs:
            f.write(f'    "{bm}|{bn}|{bk}|{stages}|{cwg}|{wm}|{wn}|{sk}|{name}"\n')
        f.write(")\n")

    print(f"Generated {len(configs)} configs -> {args.output}")

if __name__ == "__main__":
    main()
